(function ensightenInit(){var ensightenOptions = {client: "hotelscom", clientId: 314, publishPath: "prod", isPublic:1, serverComponentLocation: "nexus.ensighten.com/hotelscom/prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/hotelscom/prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "true", registryNs : "ensBootstraps", generatedOn : "Thu Mar 22 21:16:18 GMT 2018", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function l(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function m(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function n(){for(var a=b.dataDefinitionIds.length,d=!0,e=0;e<a;e++){var c=b.dataDefinitions[b.dataDefinitionIds[e]];if(!c||
null==c.endRegistration){d=!1;break}}d&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=f.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:f.interval||100,erLoc:f.errorLocation||c.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||c.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||c.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.runRuleIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var d=0;d<a.dependencies.length;d++)if(!1===a.dependencies[d]())return;
a.execute()}};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;c.DependencyNotAvailableException=l;m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.BeaconException=m;c.checkForInvalidDependencies=function(a,d,e,h){for(a=0;a<e.length;a++)if("DEPENDENCYNEVERAVAILABLE"===e[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(h[a])),d&&-1!==d&&c.allDeploymentIds.push(d),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var d=(c.currSec||0)%20,b=c.options.beaconSamplingSeedValue;-1===b?a=!0:0!==d&&0===b%d&&(a=!0)}catch(h){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(d){window[ensightenOptions.ns].reportException(d)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(c.runDeploymentIds.push(this.deploymentId),c.runRuleIds.push(this.id)),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);
-1!==a.deploymentId&&c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};b.getRuleList=function(){return c.ruleList};b.clearRuleList=function(){c.ruleList=[]};b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunRuleIds=function(){return c.runRuleIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:
!1};c.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);
this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,d,e,h){var p=
document.getElementsByTagName("script"),g;h=void 0!==h?h:!0;if(void 0!==d?d:1)for(g=0;g<p.length;g++)if(p[g].src===a&&p[g].readyState&&/loaded|complete/.test(p[g].readyState))return;if(e){e=1==e&&"object"==typeof b.scDataObj?b.scDataObj:e;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));d=window.location.href;"object"===typeof e&&e.PageID&&(d=e.PageID,delete e.PageID);if("object"===typeof e)for(g in e){g=~d.indexOf("#")?d.slice(d.indexOf("#"),d.length):"";d=d.slice(0,g.length?d.length-g.length:
d.length);d+=~d.indexOf("?")?"&":"?";for(k in e)d+=k+"="+e[k]+"&";d=d.slice(0,-1)+g;break}a+="?";h&&(a+="r="+c.rand+"&");a+="ClientID="+encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(d)}(function(a,b,d){var e=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in e){if(!e[0]){setTimeout(arguments.callee,25);return}e=e[0]}var a=b.createElement("script");a.src=d;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};e.insertBefore(a,
e.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,e){var d=document.getElementsByTagName("script"),c;e=d[0];for(c=0;c<d.length;c++)if(d[c].src===a&&d[c].readyState&&/loaded|complete/.test(d[c].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;d.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.onload=d.onreadystatechange=function(){if(!this.readyState||
"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(g){window[ensightenOptions.ns].reportException(g)}}};e.parentNode.insertBefore(d,e)};b.unobtrusiveAddEvent=function(a,b,e){try{var d=a[b]?a[b]:function(){};a[b]=function(){e.apply(this,arguments);return d.apply(this,arguments)}}catch(p){window[ensightenOptions.ns].reportException(p)}};b.anonymous=function(a,d){return function(){try{b.currentRuleId=
d?d:"anonymous",a()}catch(e){window[ensightenOptions.ns].reportException(e)}}};b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,d,e){if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:e||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var d,e=0;e<a.length;++e)if(d=b.getRule(parseInt(a[e],10)),!d||!d.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,
h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,d,e,h,f){var g=[];if(!c.checkForInvalidDependencies(d,h,e,f)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===
typeof a)a=new b.Rule({id:d||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,d,e,f,p){var g=[];if(!c.checkForInvalidDependencies(d,f,e,p)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(e)});if("function"===typeof a)a=new b.Rule({id:d||-1,deploymentId:f||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var d=a.length,e=0;e<d;e++){var c=a[e];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var f=!1,g=b.dataDefinitionIds.length,l=0;l<g;l++)if(b.dataDefinitionIds[l]===c){f=!0;break}f||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;n()};b.DataDefinition=function(a,b){this.id=
a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,d){var e=b.dataDefinitions[d];e||(e=new b.DataDefinition(d,a),b.dataDefinitions[d]=e);e.startRegistrationTime||(e.startRegistration(),e.registrationFn(),e.endRegistration());b.pageSpecificDataDefinitionsSet&&n()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=
!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,e=a.length;b<e;b++)if(a[b].src&&a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&
"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=
function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var r=function(){var a=[],b=!1,e=!1;return{add:function(d){b&&!e?d():"function"==typeof d&&(a[a.length]=d)},exec:function(){e=!0;do{var d=a;a=[];b=!0;for(var c=0;c<d.length;c++)try{d[c].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);e=!1},haveRun:function(){return b}}};b.new_fArray=
function(){return r()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?
c.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(d){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",
function(){window[ensightenOptions.ns].callOnDOMLoaded()}));document.readyState&&"complete"===document.readyState&&(b.executionState.DOMParsed=!0,b.executionState.DOMLoaded=!0);"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],d,e,h,l,g=0;g<c.ruleList.length;++g)e=c.ruleList[g],h=e.executionData.hasRun?"1":"0",l=e.deploymentId.toString()+"|"+e.id.toString()+"|"+h,a.push(l);
d="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+d+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(q){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new c.BeaconException(q),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},l=f.navigationStart||0,m={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",fetchStart:"fs",
loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};var n="&ns="+encodeURIComponent(f.navigationStart);for(var c in m)if(void 0!==f[c]){var b=f[c]-l;n+="&"+m[c]+"="+(0<b?encodeURIComponent(b):0)}else n+="&"+m[c]+"=-1";window[ensightenOptions.ns].timing=n;c=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";n=f.indexOf(".com/");l=f.indexOf("/code/");f=f.substring(n+4,l)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+c+f)}}});
	
  /*
   MIT License (c) copyright 2013 original author or authors */
  window[ensightenOptions.ns].data||(window[ensightenOptions.ns].when=function(){function f(a,b,d,c){return l(a).then(b,d,c)}function p(a){this.then=a}function l(a){return c(function(b){b(a)})}function c(b){function g(a){k&&(r=e(a),d(k,r),k=u)}function f(a){g(h(a))}function q(b){k&&d(k,a(b))}var r,k=[];try{b(g,f,q)}catch(E){f(E)}return new p(function(a,b,d){return c(function(c,g,e){k?k.push(function(f){f.then(a,b,d).then(c,g,e)}):n(function(){r.then(a,b,d).then(c,g,e)})})})}function e(a){return a instanceof
  p?a:a!==Object(a)?m(a):c(function(b,d,c){n(function(){try{var g=a.then;"function"===typeof g?z(g,a,b,d,c):b(m(a))}catch(y){d(y)}})})}function m(a){var b=new p(function(d){try{return"function"==typeof d?e(d(a)):b}catch(D){return h(D)}});return b}function h(a){var b=new p(function(d,c){try{return"function"==typeof c?e(c(a)):b}catch(F){return h(F)}});return b}function a(b){var d=new p(function(c,g,e){try{return"function"==typeof e?a(e(b)):d}catch(y){return a(y)}});return d}function d(a,b){n(function(){for(var d,
  c=0;d=a[c++];)d(b)})}function b(a,b,d,g,e){q(2,arguments);return f(a,function(a){return c(function(d,c,g){function e(a){h(a)}function q(a){u(a)}var k;var n=a.length>>>0;var t=Math.max(0,Math.min(b,n));var w=[];var x=n-t+1;var m=[];if(t){var h=function(a){m.push(a);--x||(u=h=r,c(m))};var u=function(a){w.push(a);--t||(u=h=r,d(w))};for(k=0;k<n;++k)k in a&&f(a[k],q,e,g)}else d(w)}).then(d,g,e)})}function t(a,b,d,c){q(1,arguments);return k(a,w).then(b,d,c)}function k(a,b){return f(a,function(a){return c(function(d,
  c,g){var e,q;var k=e=a.length>>>0;var r=[];if(k){var n=function(a,e){f(a,b).then(function(a){r[e]=a;--k||d(r)},c,g)};for(q=0;q<e;q++)q in a?n(a[q],q):--k}else d(r)})})}function n(a){1===x.push(a)&&A(g)}function g(){for(var a,b=0;a=x[b++];)a();x=[]}function q(a,b){for(var d,c=b.length;c>a;)if(d=b[--c],null!=d&&"function"!=typeof d)throw Error("arg "+c+" must be a function");}function r(){}function w(a){return a}f.defer=function(){var a,b;var d={promise:u,resolve:u,reject:u,notify:u,resolver:{resolve:u,
  reject:u,notify:u}};d.promise=a=c(function(c,g,e){d.resolve=d.resolver.resolve=function(d){if(b)return l(d);b=!0;c(d);return a};d.reject=d.resolver.reject=function(d){if(b)return l(h(d));b=!0;g(d);return a};d.notify=d.resolver.notify=function(a){e(a);return a}});return d};f.resolve=l;f.reject=function(a){return f(a,h)};f.join=function(){return k(arguments,w)};f.all=t;f.map=k;f.reduce=function(a,b){var d=z(B,arguments,1);return f(a,function(a){var c=a.length;d[0]=function(a,d,g){return f(a,function(a){return f(d,
  function(d){return b(a,d,g,c)})})};return G.apply(a,d)})};f.any=function(a,d,c,g){return b(a,1,function(a){return d?d(a[0]):a[0]},c,g)};f.some=b;f.isPromise=function(a){return a&&"function"===typeof a.then};p.prototype={otherwise:function(a){return this.then(u,a)},ensure:function(a){function b(){return l(a())}return this.then(b,b).yield(this)},yield:function(a){return this.then(function(){return a})},spread:function(a){return this.then(function(b){return t(b,function(b){return a.apply(u,b)})})},always:function(a,
  b){return this.then(a,a,b)}};var u;var x=[];var H=setTimeout;var A="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(a){H(a,0)};var v=Function.prototype;var C=v.call;var z=v.bind?C.bind(C):function(a,b){return a.apply(b,B.call(arguments,2))};v=[];var B=v.slice;var G=v.reduce||function(a){var b=0;var d=Object(this);var c=d.length>>>0;var g=arguments;if(1>=g.length)for(;;){if(b in
  d){g=d[b++];break}if(++b>=c)throw new TypeError;}else g=g[1];for(;b<c;++b)b in d&&(g=a(g,d[b],b,d));return g};return f}(),function(){function f(c,f){return l.all(f||[],function(e){return c.apply(null,e)})}function p(e){var m=c.call(arguments,1);return function(){return f(e,m.concat(c.call(arguments)))}}var l=window[ensightenOptions.ns].when;var c=[].slice;l.apply=f;l.call=function(e){return f(e,c.call(arguments,1))};l.lift=p;l.bind=p;l.compose=function(e){var m=c.call(arguments,1);return function(){var h=
  c.call(arguments);h=f(e,h);return l.reduce(m,function(a,d){return d(a)},h)}}}(),window[ensightenOptions.ns].data=function(f,p){function l(a,d){this.name="DataDefinitionException";this.message=d||"Data definitions cannot be resolved as there are invalid id(s): "+a}var c={engines:{memory:{get:function(a){if(e.utils.isArray(a)){for(var d=[],b=0;b<a.length;b++)d.push(c.data[a[b]]);return f[ensightenOptions.ns].when.resolve(d)}d=c.dataDefinitions[a]||{storage:{get:function(){}}};d=d.storage.get(d);c.data[a]=
  d;return f[ensightenOptions.ns].when.resolve(c.data[a])},set:function(a,d){if(e.utils.isArray(a))for(var b in a)c.data[a[b]]=d[b];else c.data[a]=d;return f[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(e.utils.isArray(a))for(var d in a)delete c.data[a[d]];else delete c.data[a];return f[ensightenOptions.ns].when.resolve(!0)},clear:function(a){c.data={};c.definitions={};return f[ensightenOptions.ns].when.resolve(!0)},all:function(){return f[ensightenOptions.ns].when.resolve(c.data)}}},
  normalizeInputArgs:function(a,d){var b={key:[],val:p},c;if(e.utils.isPlainObject(a))for(c in b.val=[],a)b.key.push(c),b.val.push(a[c]);else e.utils.isArray(a),b.key=a,b.val=d;return b},definitions:{},data:{}},e={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(d){return a}}}},m=function(){return f[ensightenOptions.ns].when.reject("Not Implemented.")};
  l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;c.DataDefinitionException=l;c.checkForInvalidDataDefinitions=function(a){e.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(f[ensightenOptions.ns].reportException(new c.DataDefinitionException(a)),!0):!1};c.collectAvailableDataDefinitions=function(a){for(var d=[],b=0;b<a.length;b++){var t=parseInt(a[b],10),k=f[ensightenOptions.ns].dataDefinitions[t];if(null===k||k===p)if(k=e.storage.session.get({id:t}),
  null!==k&&k!==p)e.set(t,k),c.dataDefinitions[t]={id:t,load:"visitor",storage:e.storage.visitor,missingDDFromCache:!0},d.push(f[ensightenOptions.ns].data.get(""+t));else return f[ensightenOptions.ns].reportException(new c.DataDefinitionException(a,"Invalid data definition used: "+t)),{promises:[],isInvalid:!0};else d.push(f[ensightenOptions.ns].data.get(a[b]))}return{promises:d,isInvalid:!1}};c.getSync=function(a){function d(a){var d=a.extract||t,c=a.transform||k,g=!1,e=null,f=null;try{e=d()}catch(v){e=
  null,g=!0}try{f=c(e)}catch(v){f=null,g=!0}g&&b.push(a.id);return f}var b=[],t=function(){return document},k=function(a){return null!==a&&a!==p?a.toString():null},n=parseInt(a);a="string"===typeof a?a.split("."):[];var g={},q="";if(!isNaN(n)&&"undefined"===typeof c.dataDefinitions[n])return f[ensightenOptions.ns].reportException(new c.DataDefinitionException(n,"Error resolving data definition: "+n+".  Does not exist on the page.")),"Data definition specified does not exist on the page";if(isNaN(n)&&
  "undefined"===typeof c.dataDefinitionsBySourceCollName[""+a[0]+"."+a[1]+"."+a[2]])return f[ensightenOptions.ns].reportException(new c.DataDefinitionException(a,"Error resolving data definition: "+a[0]+"."+a[1]+"."+a[2]+".  Does not exist on the page.")),"Data definition specified does not exist on the page";isNaN(n)?3==a.length&&(g=e.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2])):g=e.getDataDefinitionById(n);q=g.load&&g.load.match(/(session|visitor)/i)&&g.storage&&g.storage.get?g.storage.get(g):
  d(g);0<b.length&&f[ensightenOptions.ns].reportException(new c.DataDefinitionException(b,"Error resolving data definitions synchronously: "+b));return q};c.dataDefinitions={};c.dataDefinitionsBySourceCollName={};e.defineEngine=function(a,d){var b,e=["get","set","remove","clear","all"];c.engines[a]=d;if(!d.returnsPromise)for(b=0;b<e.length;b++){var k=e[b];d[k]=f[ensightenOptions.ns].when.lift(d[k])}};e.storage={instance:{set:function(a,d){},get:function(a){return c.getSync(a.id)}},page:{set:function(a,
  d){},get:function(a){return c.data[a.id]}},session:{set:function(a,d){var b=e.storage.session.get({id:a}),c=new Date,k=c.getTime();c.setTime(k+18E5);null!=b&&(d=b);f[ensightenOptions.ns].data.cookie.utils.set(a,d,{expires:c.toGMTString()});b={expires:c.getTime(),value:d};f[ensightenOptions.ns].data.local.utils.set(a,b)},get:function(a){var d=f[ensightenOptions.ns].data.cookie.utils.get(a.id),b=f.JSON&&f.JSON.stringify?f.JSON:f[ensightenOptions.ns].JSON;b=b||{};var c=new Date;c=c.getTime();if(null===
  d){try{var e=b.parse(f[ensightenOptions.ns].data.local.utils.get(a.id))}catch(n){e=null}null!=e&&(e.expires=+e.expires,c<=e.expires?d=e.value:""==e.expires&&e.value!=p?d=e.value:f[ensightenOptions.ns].data.local.utils.remove(a.id))}return d}},visitor:{set:function(a,d){var b=e.storage.session.get({id:a});null!=b&&(d=b);f[ensightenOptions.ns].data.cookie.utils.set(a,d);f[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:d})},get:function(a){return e.storage.session.get(a)}}};e.getEngine=
  e.engine=function(a){return a?c.engines[a]||{get:m,set:m,remove:m,clear:m,all:m}:c.engines};e.all=function(a){return f[ensightenOptions.ns].data.engine(a||"memory").all()};e.get=function(a,d,b){d=d||"memory";b=b||{};-1<a.indexOf(",")&&(a=a.split(","));a=c.normalizeInputArgs(a);return b.wait?c.getWait(a.key,f[ensightenOptions.ns].data.engine(d),b):c.data&&c.data.hasOwnProperty(a.key)?f[ensightenOptions.ns].data.engine(d).get(a.key):c.getWaitForKey(a.key,f[ensightenOptions.ns].data.engine(d),b)};c.getWait=
  function(a,d,b){var c=+new Date,k=f[ensightenOptions.ns].when.defer(),n=function(){var c=d.get(a);if(-1===b.wait)return c;c.then(function(a){b.setCheck(a)?k.resolve(a):setTimeout(g,b.interval)},function(a){setTimeout(g,b.interval)})},g=function(){var a=+new Date-c;-1!==b.wait&&a<b.wait?n():k.reject("Timeout")};b.interval=b.interval||500;b.wait=b.wait||5E3;e.utils.isArray(a)?b.setCheck=b.setCheck||function(a){for(var b=!0,d=0;d<a.length;d++)b=b&&!!a[d];return b}:b.setCheck=b.setCheck||function(a){return!!a};
  n();return k.promise};c.getWaitForKey=function(a,d,b){var e=f[ensightenOptions.ns].when.defer(),k=function(){if(c.data&&c.data.hasOwnProperty(a)){var g=d.get(a);if(-1===b.wait)return g;g.then(function(a){e.resolve(a)},function(a){e.reject(a)})}else setTimeout(n,b.interval)},n=function(){k()};b.interval=b.interval||100;b.wait=b.wait||1;k();return e.promise};e.set=function(a,d,b){var e=c.normalizeInputArgs(a,d);Array.prototype.slice.call(arguments);return f[ensightenOptions.ns].data.engine(b||"memory").set(e.key,
  e.val)};e.remove=function(a,d){return f[ensightenOptions.ns].data.engine(d||"memory").remove(a)};e.clear=function(a){return f[ensightenOptions.ns].data.engine(a||"memory").clear()};e.define=function(a,d){d&&(a.name=d.id||d.name);if(!a.name)return f[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));a.id=a.name;var b=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return f[ensightenOptions.ns].when.resolve()};
  a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=f[ensightenOptions.ns].data.engine("memory");a.storage=e.storage[b.toLowerCase()]||e.storage.page;var h=a.extract||function(){return document},k=a.transform||function(a){return a},n=function(b,d){var c=[];c.push(a.persist.set(b,d));a.storage.set(a.id,d);"object"==typeof f[ensightenOptions.ns].data.dataExport&&f[ensightenOptions.ns].data.dataExport(b,d,a.collection);f[ensightenOptions.ns].when.all(c).then(function(a){g.resolve(a)},
  function(a){g.reject(a)})},g=f[ensightenOptions.ns].when.defer();try{var q=a.trigger()}catch(r){f[ensightenOptions.ns].reportException(new c.DataDefinitionException(null,'"'+r+'" error caught in Data Definition trigger: '+a.dataDefName+", ID:"+a.id+". Using bottom of body trigger.")),q=f[ensightenOptions.ns].data.bottomOfBodyTrigger()}q.then(function(){g.resolve(f[ensightenOptions.ns].when.reduce([function(){try{return h()}catch(r){return f[ensightenOptions.ns].reportException(new c.DataDefinitionException(null,
  '"'+r+'" error caught in Data Definition extractor: '+a.dataDefName+", ID:"+a.id+".")),null}}(),function(){try{return k.apply(this,arguments)}catch(r){return f[ensightenOptions.ns].reportException(new c.DataDefinitionException(null,'"'+r+'" error caught in Data Definition transformer: '+a.dataDefName+", ID "+a.id+".")),null}},n],function(b,d,c,e){if(1==c)return d(b);2==c&&d(a.name,b)}))},function(a){g.reject(a)});c.dataDefinitions[a.id]=a;c.dataDefinitionsBySourceCollName[""+a.source+"."+a.collection+
  "."+a.dataDefName]=a;return g.promise};e.checkConditions=function(a){var d,b={lt:function(a,b){var d=+a,e=+b;return isNaN(d)||isNaN(e)?(f[ensightenOptions.ns].reportException(new c.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+b)),!1):d<e},gt:function(a,b){var d=+a,e=+b;return isNaN(d)||isNaN(e)?(f[ensightenOptions.ns].reportException(new c.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+
  b)),!1):d>e},eql:function(a,b){return a==b},exists:function(a,b){return null==a||a==p||""==a?!1:!0},re:function(a,b,d){b=new RegExp(b,d?"i":"");try{return a.match(b)}catch(q){return!1}},starts:function(a,d,c){d=e.utils.escapeRegEx(d);return b.re(a,"^"+d,c)},ends:function(a,d,c){d=e.utils.escapeRegEx(d);return b.re(a,d+"$",c)},contains:function(a,d,c){d=e.utils.escapeRegEx(d);return b.re(a,".*"+d+".*",c)}};b.is=b.eql;b["starts with"]=b.starts;b["ends with"]=b.ends;b["is greater than"]=b.gt;b["is less than"]=
  b.lt;b.matches=b.re;for(d=0;d<a.values.length;d++){var h=(a.customComparator?a.customComparator[d]?a.customComparator[d]:b[a.comparators[d]]:b[a.comparators[d]])(a.values[d],a.compareTo[d],a.caseInsensitive?a.caseInsensitive[d]||!1:!1);a.not[d]&&(h=!h);if(!h)return!1}return!0};e.triggerPromise=function(a,d,b){b=b||5E3;var c=+new Date,e=f[ensightenOptions.ns].when.defer();(function(){var f=a();f!=d?e.resolve(f):+new Date-c<b?setTimeout(arguments.callee,200):e.reject("timed out")})();return e.promise};
  e.timeoutPromise=function(a,d){var b=f[ensightenOptions.ns].when.defer();d=d||800;a.then(b.resolve,b.reject);setTimeout(function(){b.reject(Error("timed out"))},d);return b.promise};e.delayTrigger=function(a){a=a||10;var d=f[ensightenOptions.ns].when.defer();setTimeout(function(){d.resolve()},a);return d.promise};e.delayUntilTrigger=function(a,d,b,c){b=b||null;c=c||200;var e=+new Date,h=f[ensightenOptions.ns].when.defer();(function(){var g=a();g!=d?h.resolve(g):b?+new Date-e<b?setTimeout(arguments.callee,
  c):h.reject("timed out"):setTimeout(arguments.callee,c)})();return h.promise};c.applyTrigger=function(a){var d=f[ensightenOptions.ns].when.defer();a(function(){d.resolve(!0)});return d.promise};e.immediateTrigger=function(){return c.applyTrigger(f[ensightenOptions.ns].bindImmediate)};e.bottomOfBodyTrigger=function(){return c.applyTrigger(f[ensightenOptions.ns].bindDOMParsed)};e.whenValueExistsTrigger=function(){return f[ensightenOptions.ns].when.resolve(this.extract())};e.afterEnsightenCompleteTrigger=
  function(){return c.applyTrigger(f[ensightenOptions.ns].bindPageSpecificCompletion)};e.afterElementsDownloadedTrigger=function(){return c.applyTrigger(f[ensightenOptions.ns].bindDOMLoaded)};e.getAllDataDefinitionsOnCurrentPage=function(){return c.dataDefinitions};e.getAllDataDefinitionsOnCurrentPage_S_C_N=function(){return c.dataDefinitionsBySourceCollName};e.getDataDefinitionById=function(a){return c.dataDefinitions[a||-1]||{}};e.getDataDefinitionBySourceCollectionName=function(a,d,b){return c.dataDefinitionsBySourceCollName[""+
  a+"."+d+"."+b]||{}};e.getDataDefinitionByPercentSyntax=function(a){a=(""+a).split("_");return 1>a.length?{}:c.dataDefinitions[a[1]]||{}};e.resolve=function(a,d){var b=this,h=null;if(!c.checkForInvalidDataDefinitions(a))if(d)f[ensightenOptions.ns].bindDataDefinitionComplete(function(){var e=c.collectAvailableDataDefinitions(a);e.isInvalid||f[ensightenOptions.ns].when.all(e.promises).then(function(e){try{d.apply(b,e)}catch(r){f[ensightenOptions.ns].reportException(new c.DataDefinitionException(a,"Error resolving data definitions: "+
  a+". Details: "+r))}},function(b){f[ensightenOptions.ns].reportException(new c.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+b))})});else{h=[];var k=a;e.utils.isArray(a)||(k=[a]);for(var m=0;m<k.length;m++)h.push(c.getSync(k[m]));return h=e.utils.isArray(a)?h:h[0]}};e.extract=function(a,d){var b="",c=function(a,b){var d=~b.indexOf("#")?b.split("#")[1]:"",c=d?0:~b.indexOf("[")?parseInt(b.match(/\[(\d+)\]/)[1]):0,e=(d?b.split("#")[0]:c?b.split("[")[0]:b).toLowerCase();
  if(a==document&&"html"==e&&0==c)return document.getElementsByTagName("html")[0];if(~b.indexOf("#"))return document.getElementById(b.split("#")[1]);var g=a.firstChild;if(!g)return null;var f=0;for(c=0!=c?c-1:c;g;){if(1==g.nodeType){if(g.tagName.toLowerCase()==e&&""!=d&&g.id==d||g.tagName.toLowerCase()==e&&f==c&&""==d)return g;g.tagName.toLowerCase()==e&&f++}g=g.nextSibling}},e=function(a,b){a=a.split("/");for(var d=c(b||document,a[1]),e=2;e<a.length;e++){if(null==d)return null;d=c(d,a[e])}return d},
  h=function(){for(var a={},b=f.document.getElementsByTagName("META")||[],d=0,c=b.length;d<c;d++){var e=b[d].name||b[d].getAttribute("property")||"";0!==e.length&&(a[e]=b[d].content)}return a}(),g=function(a){var b=h[a];if(b)return b;b=f.document.getElementsByTagName("META")||[];for(var d=0,c=b.length;d<c;d++){var e=b[d].name||b[d].getAttribute("property")||"";if(a==e)return b[d].content}},q=function(a){return(val=(new RegExp("&"+a+"=([^&]*)")).exec(f.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:
  ""},r=function(a){return(val=(new RegExp("^"+a+"=.*|;\\s*"+a+"=.*")).exec(f.document.cookie))?val[0].split("=")[1].split(";")[0]:""},m=function(a){(a=l(a))&&a.nodeType&&1==a.nodeType&&(a=a.value||a.innerHTML||"");return a.toString().replace(/\n|\r|\s\s+/g,"")||""},l=function(a){var b="";if(0==a.indexOf("/HTML/BODY"))b=e(a);else try{b=eval(a)}catch(A){b=""}return b};try{return d?"meta"==d?b=g(a):"cookie"==d?b=r(a):"param"==d?b=q(a):"content"==d?b=m(a):"event"==d?b=l(a):"var"==d&&(b=f[a]):b=g(a)||r(a)||
  q(a)||m(a)||l(a)||f[a]||"",b||""}catch(x){return""}};if("undefined"==typeof h)var h={exports:{}};return e}(window),window[ensightenOptions.ns].data.defineEngine("store",function(){function f(a){return function(){var d=Array.prototype.slice.call(arguments,0);d.unshift(b);k.appendChild(b);b.addBehavior("#default#userData");b.load(h);d=a.apply(store,d);k.removeChild(b);return d}}function p(a){return a.replace(l,"___")}var l=RegExp("[!\"#$%&'()*+,/\\\\:;<=>?@[\\]^`{|}~]","g"),c={},e=window,m=e.document,
  h="localStorage",a,d=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};c.set=function(a,b){};c.get=function(a){};c.remove=function(a){};c.clear=function(){};try{if(h in e&&e[h]){var b=e[h];c.set=function(a,c){var e,g=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(d(a)){var f=0;for(e=a.length;f<e;f++)b.setItem(a[f],"string"===typeof c[f]?c[f]:g.stringify(c[f]))}else b.setItem(a,"string"===typeof c?c:g.stringify(c))};c.get=function(a){if(d(a)){var c=
  {},e;var f=0;for(e=a.length;f<e;f++)c[a[f]]=b.getItem(a[f]);return c}return b.getItem(a)};c.remove=function(a){if(d(a)){var c;var e=0;for(c=a.length;e<c;e++)b.removeItem(a[e])}else b.removeItem(a)};c.clear=function(){b.clear()};c.all=function(){return b}}else if("globalStorage"in e&&e.globalStorage)b=e.globalStorage[e.location.hostname],c.set=function(a,c){if(d(a)){var e;var f=0;for(e=a.length;f<e;f++)b[a[f]]=c[f]}else b[a]=c},c.get=function(a){if(d(a)){var c={},e;var f=0;for(e=a.length;f<e;f++)c[a[f]]=
  b[a[f]]&&b[a[f]].value;return c}return b[a]&&b[a].value},c.remove=function(a){if(d(a)){var c;var e=0;for(c=a.length;e<c;e++)delete b[a[e]]}else delete b[a]},c.clear=function(){for(var a in b)delete b[a]},c.all=function(){return b};else if(m.documentElement.addBehavior){try{var t=new ActiveXObject("htmlfile");t.open();t.write('<script>document.w=window\x3c/script><iframe src="/favicon.ico"></frame>');t.close();var k=t.w.frames[0].document;b=k.createElement("div")}catch(g){b=m.createElement("div"),
  k=m.body}c.set=f(function(a,b,e){if(d(b)){var f;var g=0;for(f=b.length;g<f;g++){fixedKey=p(b[g]);if(void 0===e[g])return c.remove(fixedKey);a.setAttribute(fixedKey,e[g]);a.save(h)}}else{fixedKey=p(b);if(void 0===e)return c.remove(fixedKey);a.setAttribute(fixedKey,e);a.save(h)}});c.get=f(function(a,b){if(d(b)){var c={},e;var f=0;for(e=b.length;f<e;f++){var g=p(b[f]);c[b[f]]=a.getAttribute(g)}return c}b=p(b);return a.getAttribute(b)});c.remove=f(function(a,b){if(d(b)){var c;var e=0;for(c=b.length;e<
  c;e++)a.removeAttribute(p(b[e])),a.save(h)}else b=p(b),a.removeAttribute(b),a.save(h)});c.clear=f(function(a){var b=a.XMLDocument.documentElement.attributes;a.load(h);for(var d=0,c;c=b[d];d++)a.removeAttribute(c.name);a.save(h)});c.all=f(function(a){for(var b=a.XMLDocument.documentElement.attributes,d={},c=0,e;e=b[c];++c){var f=p(e.name);d[e.name]=a.getAttribute(f)}return d})}}catch(g){}var n={};for(a in c)n[a]=c[a];n.testStorage=function(){try{var a="tk_"+Math.ceil(5E7*Math.random());n.set(a,"test");
  if("test"===n.get(a))return n.remove(a),!0}catch(q){}return!1};c.utils=n;return window[ensightenOptions.ns].data.local=c}()),window[ensightenOptions.ns].data.defineEngine("cookie",function(f,p){var l=function(){return l.get.apply(l,arguments)},c=l.utils={isArray:Array.isArray||function(c){return"[object Array]"===Object.prototype.toString.call(c)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(c){return Array.prototype.slice.call(c)},getKeys:Object.keys||function(c){var e=
  [],f="";for(f in c)c.hasOwnProperty(f)&&e.push(f);return e},escape:function(c){return String(c).replace(/[,;"\\=\s%]/g,function(c){return encodeURIComponent(c)})},retrieve:function(c,f){return null==c?f:c},getAllCookies:function(){if(""===f.cookie)return{};for(var c=f.cookie.split("; "),m={},h=0,a=c.length;h<a;h++){var d=c[h].split("=");m[decodeURIComponent(d[0])]=decodeURIComponent(d[1])}return m},set:function(e,m,h){h=h||-1;if(c.isPlainObject(e))for(var a in e)e.hasOwnProperty(a)&&l.set(a,e[a],
  m);else if(c.isArray(e)){var d;a=0;for(d=e.length;a<d;a++)l.set(e[a],m[a],h)}else{a=h.expires!==p?h.expires:l.defaults.expires||"";"number"===typeof a&&(a=new Date(a));a=c.isPlainObject(a)&&"toGMTString"in a?";expires="+a.toGMTString():c.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;d=(d=h.path||l.defaults.path)?";path="+d:"";var b=h.domain||l.defaults.domain;b=b?";domain="+b:"";h=h.secure||l.defaults.secure?";secure":"";f.cookie=c.escape(e)+"="+c.escape(m)+a+d+b+h}},
  get:function(e,f){f=f||p;var h=c.getAllCookies();if(c.isArray(e)){for(var a={},d=0,b=e.length;d<b;d++)a[e[d]]=c.retrieve(h[e[d]],f),a[e[d]]===p&&(a[e[d]]=null);return a}a=c.retrieve(h[e],f);return a===p?null:a},getGMTString:function(c){var e=new Date;e.setTime(e.getTime()+864E5*c);return e.toGMTString()}};l.defaults={path:"/",expires:c.getGMTString(90)};l.set=function(e,f){c.set(e,f)};l.remove=function(e){e=c.isArray(e)?e:c.toArray(arguments);for(var f=0,h=e.length;f<h;f++)c.set(e[f],"",{expires:-1})};
  l.clear=function(){return l.remove(c.getKeys(c.getAllCookies()))};l.get=function(e,f){return c.get(e,f)};l.all=function(){return c.getAllCookies()};l.utils=c;return window[ensightenOptions.ns].data.cookie=l}(document)));
		
window[ensightenOptions.ns].ensEvent||(window[ensightenOptions.ns].ensEvent=function(p,u){var k={queue:{},pollQueue:{},pushTrigger:function(b,c){if("[object Array]"===Object.prototype.toString.call(b)){for(var g=0;g<b.length;g++)k.pushTrigger(b[g],c);return!0}if("string"!=typeof b)return!1;this.queue[b]=this.queue[b]||{fn:[]};"function"==typeof c&&this.queue[b].fn.push(c);return!0},callTrigger:function(b,c,g){if("string"!=typeof b)return!1;b=k.queue[b];if("object"==typeof b&&b.fn&&b.fn.length&&(0!=
b.fireOnFirstSet&&c==u||c!=u&&0!=b.fireOnUpdate))for(c=0;c<b.fn.length;c++)try{b.fn[c].call(this)}catch(n){p[ensightenOptions.ns].reportException(n)}},setPollOptions:function(b,c,g){this.queue[b]=this.queue[b]||{fn:[]};this.queue[b].fireOnFirstSet=c;this.queue[b].fireOnUpdate=g},callPoll:function(b,c,g,p,r){if("string"==typeof b&&c&&c.length&&!(1>c.length)){for(var n=0;n<c.length;n++)k.setPollOptions(c[n],p,r);k.pushWatch(b,c,g)}},pushWatch:function(b,c,g){this.pollQueue[b]||(this.pollQueue[b]={previousVal:u,
eventArr:[],valueFn:g});this.pollQueue[b].eventArr=this.pollQueue[b].eventArr.concat(c);this.pollQueue[b].valueFn=g},globalWatch:function(){setInterval(function(){for(var b in k.pollQueue){var c=k.pollQueue[b],g=c.valueFn(b);if(c.previousVal!==g&&null!==g&&""!==g){for(var n=0;n<c.eventArr.length;n++)k.callTrigger.call(p,c.eventArr[n],c.previousVal,g);k.pollQueue[b].previousVal=g}}},500)}};k.globalWatch();return{add:function(b,c){return k.pushTrigger(b,c)},get:function(b){return k.queue[b]},trigger:function(b,
c){return k.callTrigger.call(c||p,b)},poll:function(b,c,g,n,r){r=r||p[ensightenOptions.ns].data.resolve;return k.callPoll(b,c,r,g,n)}}}(window),function(p,u,k){u[p]=k()}("qwery",window[ensightenOptions.ns],function(){function p(){this.c={}}function u(a){return H.g(a)||H.s(a,"(^|\\s+)"+a+"(\\s+|$)",1)}function k(a,d){for(var e=0,f=a.length;e<f;e++)d(a[e])}function b(a){for(var d=[],e=0,f=a.length;e<f;++e)l(a[e])?d=d.concat(a[e]):d[d.length]=a[e];return d}function c(a){for(var d=0,e=a.length,f=[];d<
e;d++)f[d]=a[d];return f}function g(a){for(;(a=a.previousSibling)&&1!=a.nodeType;);return a}function n(a,d,e,f,b,h,l,c,g,k,y){var I,B,m;if(1!==this.nodeType||d&&"*"!==d&&this.tagName&&this.tagName.toLowerCase()!==d||e&&(I=e.match(Q))&&I[1]!==this.id)return!1;if(e&&(m=e.match(R)))for(a=m.length;a--;)if(!u(m[a].slice(1)).test(this.className))return!1;if(g&&v.pseudos[g]&&!v.pseudos[g](this,y))return!1;if(f&&!l)for(B in g=this.attributes,g)if(Object.prototype.hasOwnProperty.call(g,B)&&(g[B].name||B)==
b)return this;return f&&!x(h,S(this,b)||"",l)?!1:this}function r(a){return J.g(a)||J.s(a,a.replace(T,"\\$1"))}function x(a,d,e){switch(a){case "=":return d==e;case "^=":return d.match(w.g("^="+e)||w.s("^="+e,"^"+r(e),1));case "$=":return d.match(w.g("$="+e)||w.s("$="+e,r(e)+"$",1));case "*=":return d.match(w.g(e)||w.s(e,r(e),1));case "~=":return d.match(w.g("~="+e)||w.s("~="+e,"(?:^|\\s+)"+r(e)+"(?:\\s+|$)",1));case "|=":return d.match(w.g("|="+e)||w.s("|="+e,"^"+r(e)+"(-|$)",1))}return 0}function q(a,
d){var e=[],f=[],b,h,l=d,c=C.g(a)||C.s(a,a.split(K)),g=a.match(L);if(!c.length)return e;var m=(c=c.slice(0)).pop();c.length&&(b=c[c.length-1].match(M))&&(l=N(d,b[1]));if(!l)return e;var y=m.match(E);var v=l!==d&&9!==l.nodeType&&g&&/^[+~]$/.test(g[g.length-1])?function(a){for(;l=l.nextSibling;)1==l.nodeType&&(y[1]?y[1]==l.tagName.toLowerCase():1)&&(a[a.length]=l);return a}([]):l.getElementsByTagName(y[1]||"*");b=0;for(m=v.length;b<m;b++)if(h=n.apply(v[b],y))e[e.length]=h;if(!c.length)return e;k(e,
function(a){t(a,c,g)&&(f[f.length]=a)});return f}function t(a,d,e,b){function l(a,b,c){for(;c=U[e[b]](c,a);)if(f(c)&&n.apply(c,d[b].match(E)))if(b){if(h=l(c,b-1,c))return h}else return c}var h;return(h=l(a,d.length-1,a))&&(!b||z(h,b))}function f(a,d){return a&&"object"===typeof a&&(d=a.nodeType)&&(1==d||9==d)}function h(a){var d=[],e;var f=0;a:for(;f<a.length;++f){for(e=0;e<d.length;++e)if(d[e]==a[f])continue a;d[d.length]=a[f]}return d}function l(a){return"object"===typeof a&&isFinite(a.length)}
function N(a,d,e){return 9===a.nodeType?a.getElementById(d):a.ownerDocument&&((e=a.ownerDocument.getElementById(d))&&z(e,a)&&e||!z(a,a.ownerDocument)&&F('[id="'+d+'"]',a)[0])}function v(a,d){var e,h;var g=d?"string"==typeof d?v(d)[0]:!d.nodeType&&l(d)?d[0]:d:m;if(!g||!a)return[];if(a===window||f(a))return!d||a!==window&&f(g)&&z(a,g)?[a]:[];if(a&&l(a))return b(a);if(e=a.match(V)){if(e[1])return(h=N(g,e[1]))?[h]:[];if(e[2])return c(g.getElementsByTagName(e[2]));if(W&&e[3])return c(g.getElementsByClassName(e[3]))}return F(a,
g)}function y(a,d){return function(e){var f,b;O.test(e)?9!==a.nodeType&&((b=f=a.getAttribute("id"))||a.setAttribute("id",b="__qwerymeupscotty"),d(a.parentNode||a,'[id="'+b+'"]'+e,!0),f||a.removeAttribute("id")):e.length&&d(a,e,!1)}}var m=document,D=m.documentElement,F,Q=/#([\w\-]+)/,R=/\.[\w\-]+/g,M=/^#([\w\-]+)$/,X=/^([\w]+)?\.([\w\-]+)$/,O=/(^|,)\s*[>~+]/,Y=/^\s+|\s*([,\s\+~>]|$)\s*/g,A=/[\s>\+~]/,P=/(?![\s\w\-\/\?&=:\.\(\)!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,T=/([.*+?\^=!:${}()|\[\]\/\\])/g,
V=new RegExp(M.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),L=new RegExp("("+A.source+")"+P.source,"g"),K=new RegExp(A.source+P.source),E=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*~]?=)['"]?([ \w\-\/\?&=:\.\(\)!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),U={" ":function(a){return a&&a!==D&&a.parentNode},">":function(a,d){return a&&a.parentNode==d.parentNode&&a.parentNode},"~":function(a){return a&&
a.previousSibling},"+":function(a,d,e,f){return a?(e=g(a))&&(f=g(d))&&e==f&&e:!1}};p.prototype={g:function(a){return this.c[a]||void 0},s:function(a,d,e){d=e?new RegExp(d):d;return this.c[a]=d}};var H=new p,J=new p,w=new p,C=new p,z="compareDocumentPosition"in D?function(a,d){return 16==(d.compareDocumentPosition(a)&16)}:"contains"in D?function(a,d){d=9===d.nodeType||d==window?D:d;return d!==a&&d.contains(a)}:function(a,d){for(;a=a.parentNode;)if(a===d)return 1;return 0},S=function(){var a=m.createElement("p");
return(a.innerHTML='<a href="#x">x</a>',"#x"!=a.firstChild.getAttribute("href"))?function(a,e){return"class"===e?a.className:"href"===e||"src"===e?a.getAttribute(e,2):a.getAttribute(e)}:function(a,e){return a.getAttribute(e)}}(),W=!!m.getElementsByClassName,Z=m.querySelector&&m.querySelectorAll,aa=function(a,d){var e=[],f,b;try{if(9===d.nodeType||!O.test(a))return c(d.querySelectorAll(a));k(f=a.split(","),y(d,function(a,d){b=a.querySelectorAll(d);1==b.length?e[e.length]=b.item(0):b.length&&(e=e.concat(c(b)))}));
return 1<f.length&&1<e.length?h(e):e}catch(ba){}return G(a,d)},G=function(a,d){var e=[],f,b;a=a.replace(Y,"$1");if(f=a.match(X)){var l=u(f[2]);f=d.getElementsByTagName(f[1]||"*");var c=0;for(b=f.length;c<b;c++)l.test(f[c].className)&&(e[e.length]=f[c]);return e}k(f=a.split(","),y(d,function(a,f,h){l=q(f,a);c=0;for(b=l.length;c<b;c++)if(9===a.nodeType||h||z(l[c],d))e[e.length]=l[c]}));return 1<f.length&&1<e.length?h(e):e};A=function(a){"undefined"!==typeof a.useNativeQSA&&(F=a.useNativeQSA?Z?aa:G:
G)};A({useNativeQSA:!0});v.configure=A;v.uniq=h;v.is=function(a,d,e){if(f(d))return a==d;if(l(d))return!!~b(d).indexOf(a);for(var c=d.split(","),h;d=c.pop();)if(h=C.g(d)||C.s(d,d.split(K)),d=d.match(L),h=h.slice(0),n.apply(a,h.pop().match(E))&&(!h.length||t(a,h,d,e)))return!0;return!1};v.pseudos={};return v}),function(){function p(f,b,c){n||(n=window[ensightenOptions.ns].qwery);var h=n;if((h=h.call(c,b,c))&&0<h.length){if("_root"==b)f=c;else if(f===c)f=void 0;else{b:{for(var l=h.length,g=0;g<l;g++)if(f===
h[g]){h=!0;break b}h=!1}h||(f.parentNode?(r++,f=p(f.parentNode,b,c)):f=void 0)}return f}return!1}function u(f,b,c,g){q[f.id]||(q[f.id]={});q[f.id][b]||(q[f.id][b]={});q[f.id][b][c]||(q[f.id][b][c]=[]);q[f.id][b][c].push(g)}function k(f,b,c,g){if(g||c)if(g)for(var h=0;h<q[f.id][b][c].length;h++){if(q[f.id][b][c][h]===g){q[f.id][b][c].pop(h,1);break}}else delete q[f.id][b][c];else q[f.id][b]={}}function b(b,c,l){if(q[b][l]){var f=c.target||c.srcElement,h,k,m={},n=k=0;r=0;for(h in q[b][l])q[b][l].hasOwnProperty(h)&&
(k=p(f,h,t[b].element))&&g.matchesEvent(l,t[b].element,k,"_root"==h,c)&&(r++,q[b][l][h].match=k,m[r]=q[b][l][h]);c.stopPropagation=function(){c.cancelBubble=!0};for(k=0;k<=r;k++)if(m[k])for(n=0;n<m[k].length;n++){if(!1===m[k][n].call(m[k].match,c)){g.cancel(c);return}if(c.cancelBubble)return}}}function c(c,h,l,n){function f(c){return function(f){b(p,f,c)}}c instanceof Array||(c=[c]);l||"function"!=typeof h||(l=h,h="_root");var p=this.id,m;for(m=0;m<c.length;m++)q[p]&&q[p][c[m]]||g.addEvent(this,c[m],
f(c[m])),n?k(this,c[m],h,l):u(this,c[m],h,l);return this}function g(b,c,l,k){if("string"==typeof b&&"function"==typeof c||"string"==typeof c)g(document).on(b,c,l,k||!1);if(!(this instanceof g)){for(var f in t)if(t[f].element===b)return t[f];x++;t[x]=new g(b,x);t[x]._on=t[x].on;t[x].on=function(b,c,f,g){var h="function"==typeof c?c:f;if("function"==typeof c?f:g)b=[b],"string"==typeof c&&b.push(c),b.push(function(b){return function(c){c.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);
if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return b.call(this);"undefined"!=typeof c.preventDefault?c.preventDefault():c.returnValue=!1;b.call(this)}}(h)),this._on.apply(this,b);else return this._on.call(this,b,c,f)};return t[x]}this.element=b;this.id=c}var n,r=0,x=0,q={},t={};g.prototype.on=function(b,g,l){return c.call(this,b,g,l)};g.prototype.off=function(b,g,l){return c.call(this,b,g,l,!0)};g.cancel=function(b){b.preventDefault();b.stopPropagation()};g.addEvent=function(b,c,g){b.element.addEventListener(c,
g,"blur"==c||"focus"==c)};g.matchesEvent=function(){return!0};g.load=function(b){setTimeout(function(b,c){return function(){if(b.nodeName&&"a"==b.nodeName.toLowerCase()){if(c&&/^javascript\s*:/.test(c))return(new Function(unescape(c))).call(window);c&&(window.location.href=c)}}}(b,b.href||""),750)};window[ensightenOptions.ns].Delegate=g}(),function(p){var u=p.addEvent;p.addEvent=function(k,b,c){if(k.element.addEventListener)return u(k,b,c);"focus"==b&&(b="focusin");"blur"==b&&(b="focusout");k.element.attachEvent("on"+
b,c)};p.cancel=function(k){k.preventDefault&&k.preventDefault();k.stopPropagation&&k.stopPropagation();k.returnValue=!1;k.cancelBubble=!0}}(window[ensightenOptions.ns].Delegate),window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate);
Bootstrapper.dataDefinitionIds = [52449,48628,45973,45974,48599,45561,1514,20301,21134,45551];Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(commonDataBlock&&commonDataBlock.page&&commonDataBlock.page.siteSection&&commonDataBlock.page.siteSection.match(/(BOOKING CONFIRMATION)|(MOB \:\: WEB \:\: BOOKING CONFIRMATION)|(TAB \:\: WEB \:\: BOOKING CONFIRMATION)/gi)){function getVisitorID(){var visitorIDvalue="";if(commonDataBlock.user.platformId!="Desktop"&&commonDataBlock.user.platformId!="Mob :: Web"&&
commonDataBlock.user.platformId!="Mob :: TabWeb")visitorIDvalue=s.visitorID;else if(typeof s.c_r("s_vi")!=="undefined")visitorIDvalue=s.c_r("s_vi").substring(7,40);else if(typeof s.c_r("f_id")!=="undefined")visitorIDvalue=s.c_r("f_id").substring(7,40);else visitorIDvalue=s.visitorID;return visitorIDvalue}Bootstrapper.siteCatBeaconData={currency:commonDataBlock&&commonDataBlock.page&&commonDataBlock.page.currency?commonDataBlock.page.currency:"currency not found",guid:commonDataBlock&&commonDataBlock.user&&
commonDataBlock.user.guid?commonDataBlock.user.guid.replace(/\"/g,""):"GUID not found",purchaseId:commonDataBlock&&commonDataBlock.booking&&commonDataBlock.booking.omniturePurchaseID?commonDataBlock.booking.omniturePurchaseID:"purchase id not found",lastTouchedMarket:commonDataBlock&&commonDataBlock.marketing&&commonDataBlock.marketing.lastTouchedMarketingCode?commonDataBlock.marketing.lastTouchedMarketingCode:"lastTouchedMarket not found",pageSiteSection:commonDataBlock&&commonDataBlock.page&&commonDataBlock.page.siteSection?
commonDataBlock.page.siteSection:"pageSiteSection not found",userLocale:commonDataBlock&&commonDataBlock.user&&commonDataBlock.user.locale?commonDataBlock.user.locale:"userLocale not found",cid:s&&s.prop5&&s.prop5!=""?s.prop5:"999998",userContext:s&&s.prop32&&s.prop32!=""?s.prop32:"usercontext not found",eVar61:s&&s.eVar61&&s.eVar61!=""?s.eVar61:"eVar61 not found"};var scBd=Bootstrapper.siteCatBeaconData;Bootstrapper.Cookies=function(){return{domain:"hotels.com"||location.hostname,get:function(k,
d){var c=document.cookie.split(";");for(var i=0;i<c.length;i++){var _c=c[i].replace(/^\s+/,"").split("\x3d");if(_c[0]==k)return!d?decodeURIComponent(_c[1]):_c[1]}return""},set:function(k,v,e){var domain=window.location.hostname;var NewDomain=domain.split(".");var domainsplit=NewDomain[1]+"."+NewDomain[2];document.cookie=k+"\x3d"+encodeURIComponent(v)+(e?";expires\x3d"+e:"")+";path\x3d/;domain\x3d"+domainsplit;return this.get(k)==v},test:function(k){return this.get(k)?true:false}}}();Bootstrapper.beaconData=
{uuid:function(){Bootstrapper.uuid=Bootstrapper.Cookies.test("ens_uuid")?Bootstrapper.Cookies.get("ens_uuid"):(new Date).getTime();if(!Bootstrapper.Cookies.test("ens_uuid"))Bootstrapper.Cookies.set("ens_uuid",Bootstrapper.uuid);return Bootstrapper.uuid},currentTimeStamp:function(){return"\x26currentTimestamp\x3d"+(new Date).getTime()},performanceInformation:function(){try{return"\x26loadEventEnd\x3d"+window.performance.timing.loadEventEnd+"\x26domComplete\x3d"+window.performance.timing.domComplete+
"\x26domContentLoadedEventEnd\x3d"+window.performance.timing.domContentLoadedEventEnd}catch(e){return"\x26perf\x3dunknown"}},cookieLength:function(){return"\x26cookieLength\x3d"+document.cookie.length},guid:"\x26guid\x3d"+(Bootstrapper.Cookies.test("guid")?Bootstrapper.Cookies.get("guid"):"GUID not found"),purchaseId:"\x26purchaseId\x3d"+(commonDataBlock&&commonDataBlock.booking&&commonDataBlock.booking.omniturePurchaseID?commonDataBlock.booking.omniturePurchaseID:"purchase id not found"),lastTouchedMarket:"\x26lastTouchedMarket\x3d"+
(commonDataBlock&&commonDataBlock.marketing&&commonDataBlock.marketing.lastTouchedMarketingCode?commonDataBlock.marketing.lastTouchedMarketingCode:"lastTouchedMarket not found"),pageSiteSection:"\x26pageSiteSection\x3d"+(commonDataBlock&&commonDataBlock.page&&commonDataBlock.page.siteSection?commonDataBlock.page.siteSection:"pageSiteSection not found"),userLocale:"\x26userLocale\x3d"+(commonDataBlock&&commonDataBlock.user&&commonDataBlock.user.locale?commonDataBlock.user.locale:"userLocale not found")};
var bd=Bootstrapper.beaconData;(new Image).src="//nexus.ensighten.com/hotelscom/ioResCT.rnc?cid\x3d314\x26uuid\x3d"+bd.uuid()+"\x26beaconType\x3dBootstrapLoad"+bd.currentTimeStamp()+bd.performanceInformation()+bd.cookieLength()+bd.guid+bd.purchaseId+bd.lastTouchedMarket+bd.pageSiteSection+bd.userLocale}},2090005,[2195221],269280,[147367]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return typeof commonDataBlock!=="undefined"?commonDataBlock.search.hotelCity:""},transform:function(val){return val?val.trim().toLowerCase():""},load:"page",trigger:Bootstrapper.data.whenValueExistsTrigger,dataDefName:"CityName",collection:"Page",source:"Manage",priv:"false"},{id:"45973"})},
45973)},-1,-1);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;var QueryString=function(){var query_string={};var query=window.location.search.substring(1);var vars=query.split("\x26");for(var i=0;i<vars.length;i++){var pair=vars[i].split("\x3d");if(typeof query_string[pair[0]]==="undefined")query_string[pair[0]]=pair[1];else if(typeof query_string[pair[0]]==="string"){var arr=[query_string[pair[0]],pair[1]];query_string[pair[0]]=
arr}else query_string[pair[0]].push(pair[1])}return query_string}();Bootstrapper.dataManager.push({name:"Ensighten Data Layer",id:"EnsightenDataLayer",data:{valuePaidUSD:{name:"valuePaidUSD",get:function(){Bootstrapper.initObj();if(typeof Bootstrapper.onPageObject.total!=="undefined"){var value=parseFloat(Bootstrapper.onPageObject.total);return value.toFixed(2)}else return""}},itineraryId:{name:"itineraryId",get:function(){if(typeof s.eVar15!=="undefined")return s.eVar15.split(":").length>0?s.eVar15.split(":")[1]:
s.eVar15;else return""}},hotelId:{name:"hotelId",get:function(){if(typeof Bootstrapper.onPageObject.items!=="undefined")return Bootstrapper.onPageObject.items[0].sku;else return""}},checkoutDate:{name:"checkoutDate",get:function(){if(typeof s.eVar42!=="undefined")return s.eVar42.split("|")[3];else return""}},checkinDate:{name:"checkinDate",get:function(){if(typeof s.eVar42!=="undefined")return s.eVar42.split("|")[2];else return""}},ltmc:{name:"ltmc",get:function(){return Bootstrapper.Cookies.get("ltmc")}},
rltmc:{name:"rltmc",get:function(){return Bootstrapper.Cookies.get("rltmc")}},marketingCode:{name:"Marketing Code",get:function(){if(QueryString.rffrid)var marketingCode=QueryString.rffrid;else if(Bootstrapper.Cookies.get("ltmc"))var marketingCode=Bootstrapper.Cookies.get("ltmc");else if(Bootstrapper.Cookies.get("rltmc"))var marketingCode=Bootstrapper.Cookies.get("rltmc");else var marketingCode=false;return marketingCode}}}})},2158718,[2195221,346205],221295,[147367,221796]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.onPageObject=[];for(var i=document.getElementsByTagName("script").length-1;i>=0;i--)if(typeof document.getElementsByTagName("script")[i].innerHTML!=="undefined")if(document.getElementsByTagName("script")[i].innerHTML.indexOf("googleAnalyticsPremium.sendTransactions")>-1){Bootstrapper.onPageObject=document.getElementsByTagName("script")[i].innerHTML;
Bootstrapper.onPageObject=Bootstrapper.onPageObject.match(/\[\{\"orderId.*/)[0];Bootstrapper.onPageObject=typeof jQuery!=="undefined"?jQuery.parseJSON(Bootstrapper.onPageObject.substring(1,Bootstrapper.onPageObject.length-1)):JSON.parse(Bootstrapper.onPageObject.substring(1,Bootstrapper.onPageObject.length-1));break}expireDate=new Date;Bootstrapper.bindDOMParsed(function(){if(typeof s.campaign!=="undefined"){var lastTouchedAffiliate2=s.campaign;if(Bootstrapper.Cookies.get("ltmc")!=lastTouchedAffiliate2){expireDate=
new Date;expireDate.setDate(expireDate.getDate()+30);Bootstrapper.Cookies.set("ltmc",lastTouchedAffiliate2,expireDate)}}if(typeof s.eVar29!=="undefined"){var lastTouchedAffiliate=s.eVar29;if(Bootstrapper.Cookies.get("fmtc")!=lastTouchedAffiliate){expireDate=new Date;expireDate.setDate(expireDate.getDate()+30);Bootstrapper.Cookies.set("fmtc",lastTouchedAffiliate,expireDate)}}})},346205,[2195221],221796,[147367]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;window.criteoID="";var dl_obj=Bootstrapper.dataManager?Bootstrapper.dataManager.getData():{};switch(dl_obj.UserLocale){case "de_AT":window.CriteoID=3631;break;case "en_AU":window.CriteoID=3797;break;case "iw_IL":window.CriteoID=14522;break;case "ar_AE":window.CriteoID=14523;break;case "nl_BE":window.CriteoID=3650;break;case "pt_BR":window.CriteoID=3196;break;case "es_CO":window.CriteoID=
3264;break;case "en_CA":window.CriteoID=3113;break;case "de_CH":window.CriteoID=3632;break;case "de_DE":window.CriteoID=2091;break;case "da_DK":window.CriteoID=10443;break;case "es_ES":window.CriteoID=2090;break;case "fi_FI":window.CriteoID=5009;break;case "fr_FR":window.CriteoID=923;break;case "es_US":window.CriteoID=5816;break;case "en_HK":window.CriteoID=19579;break;case "en_IE":window.CriteoID=7863;break;case "en_IN":window.CriteoID=7484;break;case "it_IT":window.CriteoID=3899;break;case "ja_JP":window.CriteoID=
3995;break;case "ko_KR":window.CriteoID=3929;break;case "es_MX":window.CriteoID=3265;break;case "en_MY":window.CriteoID=19555;break;case "nl_NL":window.CriteoID=1078;break;case "no_NO":window.CriteoID=10444;break;case "en_NZ":window.CriteoID=5558;break;case "pl_PL":window.CriteoID=3630;break;case "ru_RU":window.CriteoID=3629;break;case "sv_SE":window.CriteoID=4832;break;case "en_SG":window.CriteoID=6674;break;case "th_TH":window.CriteoID=12019;break;case "tr_TR":window.CriteoID=3633;break;case "zh_HK":window.CriteoID=
7775;break;case "en_GB":window.CriteoID=935;break;case "es_AR":window.CriteoID=23639;break;case "en_US":window.CriteoID=2709;break;case "en_TH":window.CriteoID=13964;break;case "zh_TW":window.CriteoID=6673;break;case "ms_MY":window.CriteoID=12022;break;case "zh_CN":window.CriteoID=14514;break}},1048193,[1516743,2389553],244528,[172463,270434]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return typeof commonDataBlock!=="undefined"?commonDataBlock.search.numRooms:""},transform:function(val){return val?val:""},load:"page",trigger:Bootstrapper.data.whenValueExistsTrigger,dataDefName:"SearchnumRooms",collection:"Global",source:"Manage",priv:"false"},{id:"45551"})},45551)},
-1,-1);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(window.location.pathname=="/booking/confirmation.html"||window.location.pathname=="/mobile/confirmation.html"){(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date;a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,
"script","//www.google-analytics.com/analytics.js","ga");var ma_obj=commonDataBlock&&commonDataBlock.marketing?commonDataBlock.marketing:{};var us_obj=commonDataBlock&&commonDataBlock.user?commonDataBlock.user:{};var bk_obj=commonDataBlock&&commonDataBlock.booking?commonDataBlock.booking:{};var dl_obj=Bootstrapper.dataManager.getData()||{};window.ensGuid=us_obj.guid;window.ensComponent="MarketingvisitMarketingCode\x3d"+dl_obj.MarketingvisitMarketingCode+"\x26MarketingvisitMarketingCode-type\x3d"+
typeof dl_obj.MarketingvisitMarketingCode+"\x26fullMarketingTrackingCode\x3d"+ma_obj.fullMarketingTrackingCode+"\x26fullMarketingTrackingCode-type\x3d"+typeof ma_obj.fullMarketingTrackingCode+"\x26lastTouchedMarketingCode\x3d"+ma_obj.lastTouchedMarketingCode+"\x26lastTouchedMarketingCode-type\x3d"+typeof ma_obj.lastTouchedMarketingCode+"\x26kwrd\x3d"+ma_obj.kwrd+"\x26kwrd-type\x3d"+typeof ma_obj.kwrd+"\x26omnitureOrderID\x3d"+bk_obj.omniturePurchaseID+"\x26custConfNo\x3d"+bk_obj.customerConfirmationNumber+
"\x26guid\x3d"+us_obj.guid+"\x26sessionId\x3d"+us_obj.sessionId+"\x26lastDLItem\x3d"+dl_obj.neverBlueData;ga("create","UA-54229817-1","auto");ga("send","pageview");ga("send","event","OnPageDataBlock",ensGuid,ensComponent)}},503375,[2195221,1516743],262717,[147367,172463]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return typeof commonDataBlock!=="undefined"?commonDataBlock.marketing.lastTouchedMarketingCode:""},load:"page",trigger:Bootstrapper.data.bottomOfBodyTrigger,dataDefName:"Last Touched Marketing Code",collection:"Global",source:"Manage",priv:"false"},{id:"21134"})},21134)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.conditionsIf=new Set;Bootstrapper.conditionsIfFalse=new Set;Bootstrapper.getQueryParam=function(e,t){if(!this.params||t){var n=t||window.location.search;var r=n.replace(/^\?/,""),i={};r=r.split("\x26");for(var s=0;s<r.length;s++){var o=r[s].split("\x3d");i[o[0]]=o[1]}if(!t)this.params=i;else return i[e]||""}return this.params[e]||""};Bootstrapper.getElementsByClassName=
function(){var root=document,className="",partial=false;for(var i=0;i<arguments.length;i++)if(typeof arguments[i]=="object")root=arguments[i];else if(typeof arguments[i]=="string")className=arguments[i];else partial=arguments[i];var elements=root.getElementsByTagName("*");var retElements=[],needle=partial?new RegExp(className):new RegExp("^"+className+"$");for(var i=0;i<elements.length;i++)if(typeof elements[i].className=="string"){var tempClass=elements[i].className||"";if(tempClass.match(needle))retElements.push(elements[i])}return retElements};
Bootstrapper.getElementXPath=function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+p)};Bootstrapper.getMinXPath=function(path){var p=path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=lastId;i>0;i--)if(!~p[i].indexOf("#")&&
!p[i].match(/^(html|body)/i))p.splice(i,1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==1)if(b.tagName.toLowerCase()==
f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};Bootstrapper.dataManager=function(){var _private={data:{},add:function(o){if(typeof o=="object"&&o.id){o.get=function(e){return Bootstrapper.dataManager.getDataElement(this.id,
e)};this.data[o.id]=o}},getObj:function(i){if(i)return _private.data[i];return _private.data},getDataElement:function(i,e){if(typeof this.data[i]=="undefined")return"";var dataObj=this.data[i].data,retVal;if(typeof dataObj=="object"){if(typeof dataObj[e]=="undefined")return"";dataObj=dataObj[e];if(typeof dataObj.get=="string"){var d=eval(dataObj.get);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod==
"function")retVal=dataObj.mod.call(d,d);else retVal=d}else if(typeof dataObj.get=="function"){var d=dataObj.get.call(this.data[i]);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=d}return retVal}},getDataLayer:function(i){var retObj={};var dataObj=this.data[i].data;for(var key in dataObj)try{retObj[key]=this.getDataElement(i,
key)}catch(e){retObj[key]=null}return retObj},getAllData:function(){var data=this.data,retObj={_d:{}};for(var key in data){retObj._d[key]={};var d=this.getDataLayer(key);for(var k in d){retObj[k]=d[k];retObj._d[key][k]=d[k]}}return retObj},getData:function(i){if(i)return this.getDataLayer(i);else return this.getAllData()},addDataElement:function(layerId,name,o){if(typeof this.data[layerId]=="object"&&typeof name=="string"&&typeof o=="object"){var d=this.data[layerId];d.data[name]=o}}},_public={push:function(dl){_private.add(dl)},
getObj:function(i){return _private.getObj(i)},getData:function(i){return _private.getData(i)},getDataElement:function(i,e){return _private.getDataElement(i,e)},addDataElement:function(layerId,name,o){return _private.addDataElement(layerId,name,o)}};return _public}();Bootstrapper.eventManager=function(){var _private={events:{},pushTrack:function(name,fn){if(typeof name!="string")return false;this.events[name]=this.events[name]||[];if(typeof fn=="function")this.events[name].push(fn);return true},callTrack:function(name){if(typeof name!=
"string")return false;var l=_private.events[name];if(typeof l=="object"&&l.length)for(var i=0;i<l.length;i++)l[i].call(this)},bind:function(layer,name,fn){var node=Bootstrapper.dataManager.getDataElement(layer,name),event=name.split("#")[1],name=name.split("#")[0],bound=typeof this.events[name]!="undefined"?true:false;if(typeof node.nodeName!="undefined"){this.pushTrack(name,fn);if(!bound)if((event=="onelementvisible"||event=="onelementexists")&&typeof Bootstrapper.propertyWatcher!="undefined"){Bootstrapper.eventManager.watch=
Bootstrapper.eventManager.watch||{};if(~event.indexOf("vis")){Bootstrapper.eventManager.watch[name]=Bootstrapper.propertyWatcher.create(function(){return node},["style","display"]);Bootstrapper.eventManager.watch[name].change=function(p,o,n){if(n!="none")Bootstrapper.eventManager.track(name,this)}}else{Bootstrapper.eventManager.watch[name]=Bootstrapper.propertyWatcher.create(function(){return node},["style","display"]);Bootstrapper.eventManager.watch[name].change=function(p,o,n){if(o=="undefined")Bootstrapper.eventManager.track(name,
this)}}}else Bootstrapper.unobtrusiveAddEvent(node,event,function(){Bootstrapper.eventManager.track(name,this)})}else if(typeof node=="object"&&typeof node.length!="undefined"){this.pushTrack(name,fn);if(!bound)for(i=0,l=node.length;i<l;i++)Bootstrapper.unobtrusiveAddEvent(node[i],event,function(){Bootstrapper.eventManager.track(name,this)})}},debug:function(name,ref){if(~window.location.search.indexOf("ensightenDebug"))console.log("::eventManager - Name:"+name+" ::eventManager - Scope:"+ref)}},_public=
{bindTracker:function(layer,name,fn){return _private.bind(layer,name,fn)},getEvent:function(name){return _private.events[name]},getAll:function(){return _private.events},track:function(name,ref){var $this=ref||window;_private.debug(name,$this);return _private.callTrack.call($this,name)}};return _public}();Bootstrapper.dataManager.map=function(){var _private={gD:{},mD:function(){var r={},e=window.document.getElementsByTagName("META")||[];for(var m=0,l=e.length;m<l;m++){var n=e[m].name||e[m].getAttribute("property")||
"";if(n.length!==0)r[n]=e[m].content}return r}(),gP:function(p){var s;return(s=(new RegExp("\x26"+p+"\x3d([^\x26]*)")).exec(window.location.search.replace(/^\?/,"\x26")))?s[0].split("\x3d")[1]:""},gC:function(c){var v;return(v=(new RegExp("^"+c+"\x3d.*|;\\s*"+c+"\x3d.*")).exec(window.document.cookie))?v[0].split("\x3d")[1].split(";")[0]:""},gT:function(g){try{return this.mD[g]||this.gC(g)||this.gP(g)||window[g]||""}catch(e){return""}},dF:function(n,d){this.gD={};for(var i in d){var val=typeof d[i]==
"string"?this.gT(d[i]):d[i]();if(~window.location.href.indexOf("ensightenDebug"))console.log(i+": "+val);this.gD[i]={name:i,get:'(function(){return("'+val+'")})()'}}Bootstrapper.dataManager.push({name:n,id:n,data:this.gD})}},_public={define:function(n,d){_private.dF(n,d)},get:function(g){return _private.gT(g)}};return _public}();window.$data=function(n,d){try{return Bootstrapper.dataManager.getDataElement(n,d)}catch(e){return""}};window.$globals=function(){return Bootstrapper.dataManager.getData("global")};
window.$getData=function(d){return Bootstrapper.dataManager.map.get(d)};Bootstrapper.dataManager.dataImport=function(O,N,T){var DM=Bootstrapper.dataManager;if(typeof DM.getObj()[N]=="undefined")DM.push({name:N,id:N,data:{}});for(var i in O)if(T!="simple"&&typeof O[i]=="object"){DM.dataImport(O[i],T=="flattened"?N:i,T);console.log(T)}else if(typeof O[i]!="object"||O[i]==null)try{eval('Bootstrapper.dataManager.addDataElement(N,i,{name:i,get:function(){try{return "'+O[i]+"\"}catch(e){return'error'}}})")}catch(e){}};
Bootstrapper.targetingNames=["Userpos","UserLocale","PagesiteSection","MarketingfullMarketingTrackingCode","MarketinglastTouchedMarketingCode","MarketingvisitMarketingCode","pos","PagepageName","Pagepage","UserplatformId","page.pageName","cdbPOS","ltmarketingCode","marketingCode","Propertycountry","Userbrand","MVTHardCodedTagMigrationFlag","MVTHardCodedTagMigrationFlagCJ","MVTssmvts"];Bootstrapper.targetingExtension=function(){var o=ensightenOptions,DL=typeof Bootstrapper.dataManager!="undefined"?
Bootstrapper.dataManager.getData():false;if(DL){delete DL["_d"];for(var i in DL){var fnd=false;for(var j=0;j<Bootstrapper.targetingNames.length;j++)if(Bootstrapper.targetingNames[j]==i){fnd=true;break}if(!fnd)delete DL[i]}}if(~document.cookie.indexOf("VTP:enabled")){if(!DL)DL={};DL["ensightenVT"]=1}if(typeof Bootstrapper.getExtraParams!="undefined"){var p=Bootstrapper.getExtraParams();if(typeof p=="object"){if(!DL)DL={};for(var i in p)DL[i]=p[i]}}Bootstrapper.insertScript("//"+(typeof ensightenOptions.serverComponentLocation!=
"undefined"?ensightenOptions.serverComponentLocation:o.nexus+"/"+o.client+"/serverComponent.php"),false,DL);try{if(commonDataBlock&&commonDataBlock.page&&commonDataBlock.page.siteSection&&commonDataBlock.page.siteSection.match(/(BOOKING CONFIRMATION)|(MOB \:\: WEB \:\: BOOKING CONFIRMATION)|(TAB \:\: WEB \:\: BOOKING CONFIRMATION)/gi)){function getVisitorID(){var visitorIDvalue="";if(commonDataBlock.user.platformId!="Desktop"&&commonDataBlock.user.platformId!="Mob :: Web"&&commonDataBlock.user.platformId!=
"Mob :: TabWeb")visitorIDvalue=s.visitorID;else if(typeof s.c_r("s_vi")!=="undefined")visitorIDvalue=s.c_r("s_vi").substring(7,40);else if(typeof s.c_r("f_id")!=="undefined")visitorIDvalue=s.c_r("f_id").substring(7,40);else visitorIDvalue=s.visitorID;return visitorIDvalue}Bootstrapper.siteCatBeaconData={currency:commonDataBlock&&commonDataBlock.page&&commonDataBlock.page.currency?commonDataBlock.page.currency:"currency not found",guid:commonDataBlock&&commonDataBlock.user&&commonDataBlock.user.guid?
commonDataBlock.user.guid.replace(/\"/g,""):"GUID not found",purchaseId:commonDataBlock&&commonDataBlock.booking&&commonDataBlock.booking.omniturePurchaseID?commonDataBlock.booking.omniturePurchaseID:"purchase id not found",lastTouchedMarket:commonDataBlock&&commonDataBlock.marketing&&commonDataBlock.marketing.lastTouchedMarketingCode?commonDataBlock.marketing.lastTouchedMarketingCode:"lastTouchedMarket not found",pageSiteSection:commonDataBlock&&commonDataBlock.page&&commonDataBlock.page.siteSection?
commonDataBlock.page.siteSection:"pageSiteSection not found",userLocale:commonDataBlock&&commonDataBlock.user&&commonDataBlock.user.locale?commonDataBlock.user.locale:"userLocale not found",cid:s&&s.prop5&&s.prop5!=""?s.prop5:"999998",userContext:s&&s.prop32&&s.prop32!=""?s.prop32:"usercontext not found",eVar61:s&&s.eVar61&&s.eVar61!=""?s.eVar61:"eVar61 not found"};var scBd=Bootstrapper.siteCatBeaconData}Bootstrapper.beaconData={uuid:function(){Bootstrapper.uuid=Bootstrapper.Cookies.test("ens_uuid")?
Bootstrapper.Cookies.get("ens_uuid"):(new Date).getTime();if(!Bootstrapper.Cookies.test("ens_uuid"))Bootstrapper.Cookies.set("ens_uuid",Bootstrapper.uuid);return Bootstrapper.uuid},currentTimeStamp:function(){return"\x26currentTimestamp\x3d"+(new Date).getTime()},performanceInformation:function(){try{return"\x26loadEventEnd\x3d"+window.performance.timing.loadEventEnd+"\x26domComplete\x3d"+window.performance.timing.domComplete+"\x26domContentLoadedEventEnd\x3d"+window.performance.timing.domContentLoadedEventEnd}catch(e){return"\x26perf\x3dunknown"}},
cookieLength:function(){return"\x26cookieLength\x3d"+document.cookie.length},guid:"\x26guid\x3d"+(Bootstrapper.Cookies.test("guid")?Bootstrapper.Cookies.get("guid"):"GUID not found"),purchaseId:"\x26purchaseId\x3d"+(commonDataBlock&&commonDataBlock.booking&&commonDataBlock.booking.omniturePurchaseID?commonDataBlock.booking.omniturePurchaseID:"purchase id not found"),lastTouchedMarket:"\x26lastTouchedMarket\x3d"+(commonDataBlock&&commonDataBlock.marketing&&commonDataBlock.marketing.lastTouchedMarketingCode?
commonDataBlock.marketing.lastTouchedMarketingCode:"lastTouchedMarket not found"),pageSiteSection:"\x26pageSiteSection\x3d"+(commonDataBlock&&commonDataBlock.page&&commonDataBlock.page.siteSection?commonDataBlock.page.siteSection:"pageSiteSection not found"),userLocale:"\x26userLocale\x3d"+(commonDataBlock&&commonDataBlock.user&&commonDataBlock.user.locale?commonDataBlock.user.locale:"userLocale not found")};var bd=Bootstrapper.beaconData||{}}catch(err){}};if(typeof Bootstrapper._getServerComponent!=
"undefined")Bootstrapper._getServerComponent=Bootstrapper.targetingExtension;else Bootstrapper.getServerComponent=Bootstrapper.targetingExtension;Bootstrapper.propertyWatcher=function(f){var g={watchers:[]},p={};g.options=f||{};g.options.interval=g.options.interval||50;g.Watcher=function(c,d){var e={};e.propertyFn=c;e.lastValue=undefined;e.options=d;e.change=function(a,b){};return e};g.doChecks=function(){for(var i=0;i<g.watchers.length;i++){var w=g.watchers[i],p=w.propertyFn?w.propertyFn():null;
if(w.lastValue!=p){w.change(w.lastValue,p);w.lastValue=p}}g.resetTimer()};g.resetTimer=function(){window.setTimeout(function(){g.doChecks()},g.options.interval)};g.addWatcher=function(a,b){var w=g.Watcher(a,b);g.watchers.push(w);return w};p={create:g.addWatcher};g.doChecks();return p}();Bootstrapper.VTconfig=Bootstrapper.VTconfig||{};Bootstrapper.VTconfig["DM"]=this.deploymentId;Bootstrapper.Cookies=function(){return{domain:""||location.hostname,get:function(k,d){var c=document.cookie.split(";");
for(var i=0;i<c.length;i++){var _c=c[i].replace(/^\s+/,"").split("\x3d");if(_c[0]==k)return!d?decodeURIComponent(_c[1]):_c[1]}return""},set:function(k,v,e){var domain=window.location.hostname;var NewDomain=domain.split(".");var domainsplit=NewDomain[1]+"."+NewDomain[2];document.cookie=k+"\x3d"+encodeURIComponent(v)+(e?";expires\x3d"+e:"")+";path\x3d/;domain\x3d"+domainsplit;return this.get(k)==v},test:function(k){return this.get(k)?true:false}}}()},2195221,147367);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var element=document.querySelector(".summary h1");return element?element.innerHTML:""},transform:function(val){return val?val.trim().toLowerCase():""},load:"page",trigger:Bootstrapper.data.whenValueExistsTrigger,dataDefName:"userinput",collection:"Page",source:"Manage",priv:"false"},
{id:"45561"})},45561)},-1,-1);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;try{var QueryString=function(){var query_string={};var query=window.location.search.substring(1);var vars=query.split("\x26");for(var i=0;i<vars.length;i++){var pair=vars[i].split("\x3d");if(typeof query_string[pair[0]]==="undefined")query_string[pair[0]]=pair[1];else if(typeof query_string[pair[0]]==="string"){var arr=[query_string[pair[0]],pair[1]];query_string[pair[0]]=
arr}else query_string[pair[0]].push(pair[1])}return query_string}()}catch(err){}Bootstrapper.dataManager.push({name:"Common Data Block Data Layer Synchronus",id:"CommonDataBlockDataLayerSynchronus",data:{PagesiteSection:{name:"PagesiteSection",get:function(){return commonDataBlock.page?commonDataBlock.page.siteSection:"could not find SiteSection"}},UserLocale:{name:"UserLocale",get:function(){return hcomClientData["common.locale"]?hcomClientData["common.locale"]:""}},Userpos:{name:"Userpos",get:function(){return commonDataBlock.user?
commonDataBlock.user.pos:"could not find POS"}},MarketinglastTouchedMarketingCode:{name:"MarketinglastTouchedMarketingCode",get:function(){if(commonDataBlock.marketing&&commonDataBlock.user)if(commonDataBlock.user.platformId==="Mob :: TabWeb"){if(commonDataBlock.marketing.fullMarketingTrackingCode)return commonDataBlock.marketing.fullMarketingTrackingCode.split(".kwrd\x3d")[0]}else return commonDataBlock.marketing.lastTouchedMarketingCode;return}},MVTHardCodedTagMigrationFlag:{name:"MVTHardCodedTagMigrationFlag",
get:function(){return"true"}},MVTHardCodedTagMigrationFlagCJ:{name:"MVTHardCodedTagMigrationFlag",get:function(){return!commonDataBlock.mvtHistory||commonDataBlock.mvtHistory.mvts.search(":2786.")==-1||commonDataBlock.mvtHistory.mvts.search(":2786.1")==-1?"false":"true"}},MVTssmvts:{name:"MVTssmvts",get:function(){return commonDataBlock.mvtHistory.ssmvts?commonDataBlock.mvtHistory.ssmvts:"could not find ssmvts "}},pos:{name:"POS",get:function(){return document.head.innerHTML.match(/h_ctx=(.*?)--\x3e/g)[0].replace(" --\x3e",
"").split("\x3d")[1].split("|")[1]}},UserplatformId:{name:"UserplatformId",get:function(){return commonDataBlock.user?commonDataBlock.user.platformId:"could not find platformId "}},Userbrand:{name:"Userbrand",get:function(){return commonDataBlock.user?commonDataBlock.user.pos.substring(0,4):"could not find brand"}},PagepageName:{name:"PagepageName",get:function(){return commonDataBlock.page?commonDataBlock.page.pageName:"could not find platformId "}},Propertycountry:{name:"Propertycountry",get:function(){return commonDataBlock.property?
commonDataBlock.property.country:"could not find country"}},MarketingfullMarketingTrackingCode:{name:"MarketingfullMarketingTrackingCode",get:function(){if(commonDataBlock.marketing)var MarketingfullMarketingTrackingCode=commonDataBlock.marketing.fullMarketingTrackingCode;else var MarketingfullMarketingTrackingCode=false;return MarketingfullMarketingTrackingCode}},MarketingvisitMarketingCode:{name:"MarketingvisitMarketingCode",get:function(){return commonDataBlock.marketing?commonDataBlock.marketing.visitMarketingCode:
"could not find hotel id"}}}})},1516743,[2195221],172463,[147367]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return typeof commonDataBlock!=="undefined"&&typeof commonDataBlock.rooms!=="undefined"?commonDataBlock.rooms.numRoomAdults:"could not find numRoomAdults"},load:"page",trigger:Bootstrapper.data.bottomOfBodyTrigger,dataDefName:"RoomnumRoomAdults",collection:"CommonDataBlockDataLayerAsynchronus",
source:"Manage",priv:"false"},{id:"48628"})},48628)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return typeof commonDataBlock!=="undefined"?commonDataBlock.user.pos:""},load:"page",trigger:Bootstrapper.data.whenValueExistsTrigger,dataDefName:"User POS",collection:"User Region",source:"Manage",priv:"false"},{id:"1514"})},1514)},-1,-1);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.Cookies=Bootstrapper.Cookies||function(){return{domain:"hotels.com"||location.hostname,get:function(k,d){var c=document.cookie.split(";");for(var i=0;i<c.length;i++){var _c=c[i].replace(/^\s+/,"").split("\x3d");if(_c[0]==k)return!d?decodeURIComponent(_c[1]):_c[1]}return""},set:function(k,v,e){var domain=window.location.hostname;var NewDomain=domain.split(".");
var domainsplit=NewDomain[1]+"."+NewDomain[2];document.cookie=k+"\x3d"+encodeURIComponent(v)+(e?";expires\x3d"+e:"")+";path\x3d/;domain\x3d"+domainsplit;return this.get(k)==v},test:function(k){return this.get(k)?true:false}}}();switch(Bootstrapper.Cookies.get("ens_splitGroup")){case "1":var cohort="80";break;case "2":var cohort="10A";break;case "3":var cohort="10B";break;default:var cohort="unexpected-cohort-value:"+Bootstrapper.Cookies.get("ens_splitGroup");break}Bootstrapper.imageRequest("//activate.hotels.com/no-content?ens\x3dcus\x26cid\x3d314\x26cohort\x3d"+
cohort+"")},2287578,[695570],293398,[241843]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(!Bootstrapper.Cookies.test("ens_splitGroup")){var expireDate=new Date;expireDate.setMonth(expireDate.getMonth()+6);var rand=Math.floor(Math.random()*10+1);if(rand>=3)Bootstrapper.Cookies.set("ens_splitGroup","1",expireDate);else{var rand2=Math.floor(Math.random()*10+1);if(rand2>=5)Bootstrapper.Cookies.set("ens_splitGroup","2",expireDate);else Bootstrapper.Cookies.set("ens_splitGroup",
"3",expireDate)}console.log("Cookie set: "+Bootstrapper.Cookies.get("ens_splitGroup"))}else console.log("Cookie already set: "+Bootstrapper.Cookies.get("ens_splitGroup"));Bootstrapper[Bootstrapper.Cookies.get("ens_splitGroup")]=true},695570,[2195221],241843,[147367]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var a="30dlt";var cookieValue=document.cookie.match("(^|;)\\s*"+a+"\\s*\x3d\\s*([^;]+)");return cookieValue?cookieValue.pop():""},load:"page",trigger:Bootstrapper.data.bottomOfBodyTrigger,dataDefName:"30DLT Marketing from Cookie",collection:"Global",source:"Manage",priv:"false"},
{id:"20301"})},20301)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){var element=document.querySelector("summary h1");return element?element.innerHTML:""},transform:function(val){return val?val.trim().toLowerCase():""},load:"page",trigger:Bootstrapper.data.whenValueExistsTrigger,dataDefName:"HotelSearchState",collection:"Page",source:"Manage",priv:"false"},
{id:"45974"})},45974)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return typeof commonDataBlock!=="undefined"&&typeof commonDataBlock.rooms!=="undefined"?commonDataBlock.rooms.numRoomChildren:"could not find numRoomChildren"},load:"page",trigger:Bootstrapper.data.bottomOfBodyTrigger,dataDefName:"RoomnumRoomChildren",collection:"CommonDataBlockDataLayerAsynchronus",
source:"Manage",priv:"false"},{id:"48599"})},48599)},-1,-1);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.registerDataDefinition(function(){Bootstrapper.data.define({extract:function(){return document.referrer},transform:function(val){return val?val:""},load:"instance",trigger:Bootstrapper.data.immediateTrigger,dataDefName:"Referring URL",collection:"Global",source:"Manage",priv:"false"},{id:"52449"})},52449)},-1,-1);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();